### PR TITLE
Adding new assessment service

### LINKED ISSUE #53: Assessment answers service
When a user completes an assessment for himself or his family members, a JSON is sent from the frontend to the backend. The assessment must expose an endpoint where this information is received.
The service will write this JSON to disk so that it can be indexed by Elasticsearch.
The service will also write the data redundantly in an SQL database in order to be able to serve the history of assessments per user.

### PR DESCRIPTION
**Pull request by andreimole**
### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes https://github.com/code4romania/stam-acasa/issues/53

Please mention the main changes this PR brings.
Adds a new service that aggregates FileService and AssessmentService
Added the new table to UserDbContext 
### How has it been tested?
It has been tested locally without docker
Please describe the tests that you ran to verify your changes.
I made a post request to the Answers api and verified that it gets persisted locally and in the database

### CODE REVIEW

**Comment by RaduCStefanescu** [comment]
@andreimole could you please update your PR with the latest changes and resolve the conflicts?

**Comment by andreimole** [comment]
Ok, încerc diseară dacă nu maine

**Comment by RaduCStefanescu** [comment]
Great!

**Comment by andreimole** [comment]
nu pare ca mai e nevoie de acest pull request. a fost dublata functionalitatea de altcineva in FormService. propun inchiderea lui.

**Comment by RaduCStefanescu** [comment]
Da, pare ca logica este deja facuta in FormService, care face toate operatiile de care avem nevoie. Am sa inchid acest PR. Multumesc de ajutor @andreimole

**Pull request closed without merging**
