### PR TITLE
Update dockerimage.frontend.yml

### LINKED ISSUE #420: Don't push to Docker Hub on PR
We should not push an image to Docker Hub [in the GitHub actions](https://github.com/code4romania/stam-acasa/blob/develop/.github/workflows/dockerimage.frontend.yml#L8-L13) when a PR is created, only when a merge is made to develop or master.

### PR DESCRIPTION
**Pull request by Utwo**
#420

### CODE REVIEW

**Comment by surdu** [comment]
There are some checks bellow that I don;t think are needed anymore. Things like:
```
if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
```

**Review by surdu — CHANGES_REQUESTED** [review]
There are some checks bellow that I don't think are needed anymore. Things like:
```
if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
```

**Comment by Utwo** [comment]
> There are some checks bellow that I don't think are needed anymore. Things like:
> 
> ```
> if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
> ```

As far as I can see, those checks are needed for pushing different docker image tags depending on branch name. If you want, I can make so that on **develop** and **master** branch we will push GIT_SHA docker tag. But I don't know how this will work with terraform.

**Comment by surdu** [comment]
Still, the check [at line 30](https://github.com/code4romania/stam-acasa/pull/449/files#diff-5c10727261cd6c76cea75ab3eb1e1401R30) looks redundant to me: the action is taken only on master and develop branch. This if will always be true.

For the others, yes, you are right

**Comment by Utwo** [comment]
> Still, the check [at line 30](https://github.com/code4romania/stam-acasa/pull/449/files#diff-5c10727261cd6c76cea75ab3eb1e1401R30) looks redundant to me: the action is taken only on master and develop branch. This if will always be true.
> 
> For the others, yes, you are right

You are right, sorry!

**Review by surdu — APPROVED** [review]

**Pull request merged**
